### ISSUE TITLE
Support GTM environment configuration

### ISSUE THREAD

**Issue by nickbreentvnz** [segment-integrations/analytics.js-integration-google-tag-manager#9]
Where the GTM `script` element is defined, add support for the GTM environment option.

Instead of:
```
var GTM = module.exports = integration('Google Tag Manager')
  .assumesPageview()
  .global('dataLayer')
  .global('google_tag_manager')
  .option('containerId', '')
  .option('trackNamedPages', true)
  .option('trackCategorizedPages', true)
  .tag('<script src="//www.googletagmanager.com/gtm.js?id={{ containerId }}&l=dataLayer">');
```

Do something like this.
```
var GTM = module.exports = integration('Google Tag Manager')
  .assumesPageview()
  .global('dataLayer')
  .global('google_tag_manager')
  .option('containerId', '')
  .option('environment', '')
  .option('trackNamedPages', true)
  .option('trackCategorizedPages', true)
  .tag('<script src="//www.googletagmanager.com/gtm.js?id={{ containerId }}&l=dataLayer&gtm_preview={{ environment }}">');
```

The caveat is that if `environment` is not specified then the entire `gtm_preview` parameter must be omitted.

**Comment by hankim813** [comment]
@nickbreentvnz thank you for bringing this up! Can you link to GA docs on this config? Would just like to know what use cases there are for adding this :)

**Comment by nickbreentvnz** [comment]
[Main documentation](https://support.google.com/tagmanager/answer/6311518?hl=en)

Our use-case is to segregate our production and multiple non-production environments to avoid cross-pollution, and to avoid having to have general use of the GTM UI's preview feature.

The actual code is provided by the GTM UI, an example of which looks like this:

>Copy the code below and paste it onto every page of your test environment.
>Paste this code as high in the <head> of the page as possible:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=AUTH_TOKEN&gtm_preview=ENVIRONMENT_ID&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXXXX');</script>
<!-- End Google Tag Manager -->
```

> Additionally, paste this code immediately after the opening <body> tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXX&gtm_auth=AUTH_TOKEN&gtm_preview=ENVIRONMENT_ID&gtm_cookies_win=x"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

Where `GTM-XXXXXX`, `AUTH_TOKEN`, `ENVIRONMENT_ID` are placeholders.

We use this internally to switch between the default and environmental variants:

```
 String extraQueryArgs = StringUtils.isNotBlank(auth) && StringUtils.isNotBlank(previewEnvironment) 
                ? String.format("&gtm_auth=%s&gtm_preview=%s&gtm_cookies_win=x", auth, env)
                : "";
```

One can infer the actual difference between the variants is just the additional query arguments.

**Comment by hankim813** [comment]
@nickbreentvnz makes sense to me. I'll add this request internal in our system and track it there!

**Comment by Peripheral1994** [comment]
@nickbreentvnz This fix is now live in production.
